#!/usr/bin/env python3
"""
Generate TypeScript/Zod schema from Pydantic validation_schemas.py.

This script extracts constraints from the backend Pydantic models
(JobCreateRequest, LLMProviderConfig, ImageProviderConfig) and emits
TypeScript/Zod code to frontend/lib/generated/job_schema.ts.

Single source of truth: app/domain/validation_schemas.py
Generated output: frontend/lib/generated/job_schema.ts
"""

import json
import sys
from pathlib import Path

from pydantic import BaseModel

# Add app to path so we can import validation schemas
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.domain.validation_schemas import (
    ImageProviderConfig,
    JobCreateRequest,
    LLMProviderConfig,
)


def format_providers_array(providers):
    """Format provider tuple as TypeScript const assertion."""
    items = ', '.join(f'"{p}"' for p in providers)
    return f"[{items}]"


def build_typescript_zod_schema():
    """Generate TypeScript/Zod schema code from Pydantic models."""

    # Extract provider enums from model literal types
    llm_providers = LLMProviderConfig.model_fields["provider"].annotation.__args__
    image_providers = ImageProviderConfig.model_fields["provider"].annotation.__args__

    # Extract field constraints
    job_fields = JobCreateRequest.model_fields

    code_lines = [
        '/**',
        ' * Auto-generated from app/domain/validation_schemas.py',
        ' *',
        ' * DO NOT EDIT MANUALLY. This file is generated by scripts/generate_schema.py',
        ' * and should be committed to version control.',
        ' */',
        'import { z } from "zod";',
        "",
        "// ---------------------------------------------------------------------------",
        "// Provider enums",
        "// ---------------------------------------------------------------------------",
        "",
    ]

    # Format provider arrays
    llm_providers_str = format_providers_array(llm_providers)
    image_providers_str = format_providers_array(image_providers)

    code_lines.append(f"export const LLM_PROVIDERS = {llm_providers_str} as const;")
    code_lines.append("")
    code_lines.append(f"export const IMAGE_PROVIDERS = {image_providers_str} as const;")
    code_lines.extend([
        "",
        "// ---------------------------------------------------------------------------",
        "// Sub-schemas",
        "// ---------------------------------------------------------------------------",
        "",
        "export const LLMProviderSchema = z.object({",
        "  provider: z.enum(LLM_PROVIDERS, {",
        '    error: "Provider must be one of: anthropic, openai, google, ollama, openai-compatible",',
        "  }),",
    ])

    # LLMProviderConfig fields
    llm_model_field = LLMProviderConfig.model_fields["model"]
    llm_api_key_field = LLMProviderConfig.model_fields["api_key"]
    llm_base_url_field = LLMProviderConfig.model_fields["base_url"]

    model_info = llm_model_field.metadata
    min_model = next(
        (m.min_length for m in model_info if hasattr(m, "min_length")), 1
    )
    max_model = next(
        (m.max_length for m in model_info if hasattr(m, "max_length")), 200
    )

    api_key_info = llm_api_key_field.metadata
    min_api_key = next(
        (m.min_length for m in api_key_info if hasattr(m, "min_length")), 1
    )
    max_api_key = next(
        (m.max_length for m in api_key_info if hasattr(m, "max_length")), 500
    )

    base_url_info = llm_base_url_field.metadata
    max_base_url = next(
        (m.max_length for m in base_url_info if hasattr(m, "max_length")), 500
    )

    code_lines.extend([
        "  model: z",
        "    .string()",
        f'    .min({min_model}, "Model name is required")',
        f'    .max({max_model}, "Model name must be at most {max_model} characters"),',
        "  api_key: z",
        "    .string()",
        f'    .min({min_api_key}, "API key is required")',
        f'    .max({max_api_key}, "API key must be at most {max_api_key} characters"),',
        "  base_url: z",
        "    .string()",
        f'    .max({max_base_url}, "Base URL must be at most {max_base_url} characters")',
        "    .optional(),",
        "});",
        "",
    ])

    # ImageProviderConfig
    img_api_key_field = ImageProviderConfig.model_fields["api_key"]
    img_api_key_info = img_api_key_field.metadata
    min_img_api_key = next(
        (m.min_length for m in img_api_key_info if hasattr(m, "min_length")), 1
    )
    max_img_api_key = next(
        (m.max_length for m in img_api_key_info if hasattr(m, "max_length")), 500
    )

    code_lines.extend([
        "export const ImageProviderSchema = z.object({",
        "  provider: z.enum(IMAGE_PROVIDERS, {",
        '    error: "Image provider must be one of: dall-e-3, replicate-flux",',
        "  }),",
        "  api_key: z",
        "    .string()",
        f'    .min({min_img_api_key}, "API key is required")',
        f'    .max({max_img_api_key}, "API key must be at most {max_img_api_key} characters"),',
        "});",
        "",
        "// ---------------------------------------------------------------------------",
        "// Main schema",
        "// ---------------------------------------------------------------------------",
        "",
        "export const JobCreateSchema = z.object({",
    ])

    # Extract constraints for each field in JobCreateRequest
    title_field = job_fields["title"]
    title_info = title_field.metadata
    title_min = next((m.min_length for m in title_info if hasattr(m, "min_length")), 1)
    title_max = next((m.max_length for m in title_info if hasattr(m, "max_length")), 500)

    topic_field = job_fields["topic"]
    topic_info = topic_field.metadata
    topic_min = next((m.min_length for m in topic_info if hasattr(m, "min_length")), 1)
    topic_max = next((m.max_length for m in topic_info if hasattr(m, "max_length")), 2000)

    audience_field = job_fields["audience"]
    audience_info = audience_field.metadata
    audience_min = next((m.min_length for m in audience_info if hasattr(m, "min_length")), 1)
    audience_max = next((m.max_length for m in audience_info if hasattr(m, "max_length")), 500)

    tone_field = job_fields["tone"]
    tone_info = tone_field.metadata
    tone_min = next((m.min_length for m in tone_info if hasattr(m, "min_length")), 1)
    tone_max = next((m.max_length for m in tone_info if hasattr(m, "max_length")), 200)

    target_chapters_field = job_fields["target_chapters"]
    target_chapters_info = target_chapters_field.metadata
    chapters_min = next((m.ge for m in target_chapters_info if hasattr(m, "ge")), 3)
    chapters_max = next((m.le for m in target_chapters_info if hasattr(m, "le")), 50)

    code_lines.extend([
        "  title: z",
        "    .string()",
        f'    .min({title_min}, "Title is required")',
        f'    .max({title_max}, "Title must be at most {title_max} characters"),',
        "  topic: z",
        "    .string()",
        f'    .min({topic_min}, "Topic is required")',
        f'    .max({topic_max}, "Topic must be at most {topic_max} characters"),',
        '  mode: z.enum(["fiction", "non_fiction"], {',
        '    error: "Mode must be fiction or non_fiction",',
        "  }),",
        "  audience: z",
        "    .string()",
        f'    .min({audience_min}, "Target audience is required")',
        f'    .max({audience_max}, "Target audience must be at most {audience_max} characters"),',
        "  tone: z",
        "    .string()",
        f'    .min({tone_min}, "Tone is required")',
        f'    .max({tone_max}, "Tone must be at most {tone_max} characters"),',
        "  target_chapters: z",
        '    .number({ error: "Target chapters must be a number" })',
        '    .int("Target chapters must be a whole number")',
        f'    .min({chapters_min}, "Minimum {chapters_min} chapters")',
        f'    .max({chapters_max}, "Maximum {chapters_max} chapters"),',
        "  llm: LLMProviderSchema,",
        "  image: ImageProviderSchema,",
        "  notification_email: z",
        "    .string()",
        '    .email("Must be a valid email address")',
        "    .optional()",
        '    .or(z.literal("")),',
        "});",
        "",
        "// ---------------------------------------------------------------------------",
        "// Derived TypeScript types — import these instead of re-declaring interfaces",
        "// ---------------------------------------------------------------------------",
        "",
        "export type LLMProviderInput = z.infer<typeof LLMProviderSchema>;",
        "export type ImageProviderInput = z.infer<typeof ImageProviderSchema>;",
        "export type JobCreateInput = z.infer<typeof JobCreateSchema>;",
    ])

    return "\n".join(code_lines) + "\n"


def main():
    """Generate and write the TypeScript schema file."""
    output_dir = Path(__file__).parent.parent / "frontend" / "lib" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = output_dir / "job_schema.ts"

    schema_code = build_typescript_zod_schema()

    output_file.write_text(schema_code)
    print(f"Generated schema: {output_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
